command_timeout = 700

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
${custom.git_status}\
${custom.jj}\
$hg_branch\
$docker_context\
$buf\
$cmake\
$container\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[battery]
disabled=true

[buf]
disabled=true

[directory]
style="bold blue"
fish_style_pwd_dir_length=1
truncate_to_repo=false

[git_branch]
disabled=true
style="bold cyan"

[cmd_duration]
disabled=true

[python]
format="via [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"

[custom.git_branch]
ignore_timeout = true
when = true
# command = "jj root >/dev/null 2>&1 || starship module git_branch"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"

[custom.git_status]
when = true
ignore_timeout = true
# command = "jj root >/dev/null 2>&1 || starship module git_status"
command = "starship module git_status"
description = "Only show git_status if we're not in a jj repo"
format = "($output )"

# [custom.jj]
# ignore_timeout = true
# description = "The current jj status"
# detect_folders = [".jj"]
# symbol = "🥋 "
# command = '''
# jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
#   separate(" ",
#     change_id.shortest(4),
#     bookmarks,
#     "|",
#     concat(
#       if(conflict, "💥"),
#       if(divergent, "🚧"),
#       if(hidden, "👻"),
#       if(immutable, "🔒"),
#     ),
#     raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
#     raw_escape_sequence("\x1b[1;32m") ++ coalesce(
#       truncate_end(29, description.first_line(), "…"),
#       "(no description set)",
#     ) ++ raw_escape_sequence("\x1b[0m"),
#   )
# '
# '''

[custom.jj]
command = "prompt"
format = "$output"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true


[git_state]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true
